alter table award_book drop foreign key FK16896B8B59E7AE0E;
alter table award_book drop foreign key FK16896B8BD3D5E38;
alter table book drop foreign key FK2E3AE938B1BD66;
alter table book drop foreign key FK2E3AE95C9F25CE;
alter table follow drop foreign key FKB45D3BB1651EA0C8;
alter table follow drop foreign key FKB45D3BB180417193;
alter table kind_book drop foreign key FKFEF0D4B459E7AE0E;
alter table kind_book drop foreign key FKFEF0D4B42BB56A2E;
alter table kind_book_kind_book drop foreign key FKCDF752E99B6E6661;
alter table kind_book_kind_book drop foreign key FKCDF752E9CC28E817;
alter table person drop foreign key FKC4E39B5538B1BD66;
alter table person drop foreign key FKC4E39B55B3B89C86;
alter table read_book drop foreign key FKBD9A27F259E7AE0E;
alter table read_book drop foreign key FKBD9A27F2DEB93ACE;
alter table topic_book drop foreign key FKCE3E0BF959E7AE0E;
alter table topic_book drop foreign key FKCE3E0BF9337B3CE6;
alter table win_award drop foreign key FKE9C3543A5C9F25CE;
alter table win_award drop foreign key FKE9C3543AAD50626;
drop table if exists award;
drop table if exists award_book;
drop table if exists book;
drop table if exists book_list;
drop table if exists country;
drop table if exists editorial;
drop table if exists follow;
drop table if exists generation;
drop table if exists image;
drop table if exists kind;
drop table if exists kind_book;
drop table if exists kind_book_kind_book;
drop table if exists person;
drop table if exists read_book;
drop table if exists topic;
drop table if exists topic_book;
drop table if exists win_award;
create table award (id bigint not null auto_increment, version bigint not null, award varchar(255) not null, primary key (id));
create table award_book (award_book_id bigint, book_id bigint);
create table book (id bigint not null auto_increment, version bigint not null, author_id bigint, editorial varchar(255), image_id bigint, isbn varchar(255) not null unique, synopsis varchar(255), title varchar(255) not null, year datetime, primary key (id));
create table book_list (id bigint not null auto_increment, version bigint not null, primary key (id));
create table country (id bigint not null auto_increment, version bigint not null, code varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
create table editorial (id bigint not null auto_increment, version bigint not null, date datetime not null, name varchar(255) not null, primary key (id));
create table follow (id bigint not null auto_increment, version bigint not null, follower_id bigint not null, leader_id bigint not null, primary key (id));
create table generation (id bigint not null auto_increment, version bigint not null, generation varchar(255) not null, primary key (id));
create table image (id bigint not null auto_increment, version bigint not null, extension varchar(255) not null, name varchar(255) not null, primary key (id));
create table kind (id bigint not null auto_increment, version bigint not null, kind varchar(255) not null, primary key (id));
create table kind_book (id bigint not null auto_increment, version bigint not null, book_id bigint not null, kind_id bigint not null, primary key (id));
create table kind_book_kind_book (kind_book_kind_books_id bigint, kind_book_id bigint);
create table person (id bigint not null auto_increment, version bigint not null, birthday datetime, country_id bigint, first_name varchar(255) not null, image_id bigint, last_name varchar(255), name varchar(255) not null, sex varchar(255) not null, class varchar(255) not null, email varchar(255) unique, user_name varchar(255) unique, primary key (id));
create table read_book (id bigint not null auto_increment, version bigint not null, book_id bigint not null, comment varchar(255) not null, reader_id bigint not null, score integer not null, primary key (id));
create table topic (id bigint not null auto_increment, version bigint not null, topic varchar(255) not null, primary key (id));
create table topic_book (id bigint not null auto_increment, version bigint not null, book_id bigint not null, topic_id bigint not null, primary key (id));
create table win_award (id bigint not null auto_increment, version bigint not null, author_id bigint not null, award_id bigint not null, year datetime not null, primary key (id));
alter table award_book add index FK16896B8B59E7AE0E (book_id), add constraint FK16896B8B59E7AE0E foreign key (book_id) references book (id);
alter table award_book add index FK16896B8BD3D5E38 (award_book_id), add constraint FK16896B8BD3D5E38 foreign key (award_book_id) references award (id);
alter table book add index FK2E3AE938B1BD66 (image_id), add constraint FK2E3AE938B1BD66 foreign key (image_id) references image (id);
alter table book add index FK2E3AE95C9F25CE (author_id), add constraint FK2E3AE95C9F25CE foreign key (author_id) references person (id);
alter table follow add index FKB45D3BB1651EA0C8 (leader_id), add constraint FKB45D3BB1651EA0C8 foreign key (leader_id) references person (id);
alter table follow add index FKB45D3BB180417193 (follower_id), add constraint FKB45D3BB180417193 foreign key (follower_id) references person (id);
alter table kind_book add index FKFEF0D4B459E7AE0E (book_id), add constraint FKFEF0D4B459E7AE0E foreign key (book_id) references book (id);
alter table kind_book add index FKFEF0D4B42BB56A2E (kind_id), add constraint FKFEF0D4B42BB56A2E foreign key (kind_id) references kind (id);
alter table kind_book_kind_book add index FKCDF752E99B6E6661 (kind_book_kind_books_id), add constraint FKCDF752E99B6E6661 foreign key (kind_book_kind_books_id) references kind_book (id);
alter table kind_book_kind_book add index FKCDF752E9CC28E817 (kind_book_id), add constraint FKCDF752E9CC28E817 foreign key (kind_book_id) references kind_book (id);
alter table person add index FKC4E39B5538B1BD66 (image_id), add constraint FKC4E39B5538B1BD66 foreign key (image_id) references image (id);
alter table person add index FKC4E39B55B3B89C86 (country_id), add constraint FKC4E39B55B3B89C86 foreign key (country_id) references country (id);
alter table read_book add index FKBD9A27F259E7AE0E (book_id), add constraint FKBD9A27F259E7AE0E foreign key (book_id) references book (id);
alter table read_book add index FKBD9A27F2DEB93ACE (reader_id), add constraint FKBD9A27F2DEB93ACE foreign key (reader_id) references person (id);
alter table topic_book add index FKCE3E0BF959E7AE0E (book_id), add constraint FKCE3E0BF959E7AE0E foreign key (book_id) references book (id);
alter table topic_book add index FKCE3E0BF9337B3CE6 (topic_id), add constraint FKCE3E0BF9337B3CE6 foreign key (topic_id) references topic (id);
alter table win_award add index FKE9C3543A5C9F25CE (author_id), add constraint FKE9C3543A5C9F25CE foreign key (author_id) references person (id);
alter table win_award add index FKE9C3543AAD50626 (award_id), add constraint FKE9C3543AAD50626 foreign key (award_id) references award (id);
